### ISSUE TITLE
a blank page when opening bokeh

### ISSUE THREAD

**Issue by ahmedahmedov** [anfederico/Stocktalk#8]
I have followed the instructions on the main page. However, the bokeh server loads only a blank page. What am I missing?

**Comment by bionicles** [comment]
same problem here. might be the path?

**Comment by bionicles** [comment]
streaming works fine.
visualize says it's working, but the bokeh isn't rendering... this seems to be an issue with bokeh

page source:
  |  
-- | --
  | <!DOCTYPE html>
  | <html lang="en">
  | <head>
  | <meta charset="utf-8">
  | <title>Bokeh Application</title>
  |  
  | <link rel="stylesheet" href="static/css/bokeh.min.css?v=06206b4cbc8ea56b6016931bd1976f7f" type="text/css" />
  | <link rel="stylesheet" href="static/css/bokeh-widgets.min.css?v=509e292d9a7ef7e9eb8382fcde7b4a6e" type="text/css" />
  | <link rel="stylesheet" href="static/css/bokeh-tables.min.css?v=aa783ffa4e290813a295a99cce2f8b5d" type="text/css" />
  |  
  | <script type="text/javascript" src="static/js/bokeh.min.js?v=15c391efcd2d880600216acd13aa97ff"></script>
  | <script type="text/javascript" src="static/js/bokeh-widgets.min.js?v=4fab6c0812b586bd3b599927148ddee2"></script>
  | <script type="text/javascript" src="static/js/bokeh-tables.min.js?v=c7b9e0042fcdcc9186ff88b239811602"></script>
  | <script type="text/javascript" src="static/js/bokeh-gl.min.js?v=2f4a9a9e9f8b300c68c4ed24b5f4979a"></script>
  | <script type="text/javascript">
  | Bokeh.set_log_level("info");
  | </script>
  | <style>
  | html {
  | width: 100%;
  | height: 100%;
  | }
  | body {
  | width: 90%;
  | height: 100%;
  | margin: auto;
  | }
  | </style>
  | </head>
  | <body>
  |  
  | <div class="bk-root">
  | <div class="bk-plotdiv" id="e255e8bd-3b64-4045-b3b2-fa58e0582f4a"></div>
  | </div>
  |  
  | <script type="application/json" id="909fea5b-65e3-4f97-b2d8-8b916f39c3e9">
  | {}
  | </script>
  | <script type="text/javascript">
  | (function() {
  | var fn = function() {
  | Bokeh.safely(function() {
  | (function(root) {
  | function embed_document(root) {
  |  
  | var docs_json = document.getElementById('909fea5b-65e3-4f97-b2d8-8b916f39c3e9').textContent;
  | var render_items = [{"elementid":"e255e8bd-3b64-4045-b3b2-fa58e0582f4a","sessionid":"XvX2FCKUGiQZOtMp2v4XlCBKXVCqCKEeDgjaEWOLc6Zm","use_for_title":true}];
  | root.Bokeh.embed.embed_items(docs_json, render_items);
  |  
  | }
  | if (root.Bokeh !== undefined) {
  | embed_document(root);
  | } else {
  | var attempts = 0;
  | var timer = setInterval(function(root) {
  | if (root.Bokeh !== undefined) {
  | embed_document(root);
  | clearInterval(timer);
  | }
  | attempts++;
  | if (attempts > 100) {
  | console.log("Bokeh: ERROR: Unable to run BokehJS code because BokehJS library is missing")
  | clearInterval(timer);
  | }
  | }, 10, root)
  | }
  | })(window);
  | });
  | };
  | if (document.readyState != "loading") fn();
  | else document.addEventListener("DOMContentLoaded", fn);
  | })();
  | </script>
  | </body>
  | </html>

**Comment by anfederico** [comment]
Going to do an update, should only be a few weeks.

**Comment by anfederico** [comment]
Please refer to new version of Stocktalk.
